# -*- coding: utf-8 -*-
"""iran_geopolitical_risk_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nDWAvC_y5YNk-j_fQVmrT_1JMSWdvkhf

# USA–Iran–India Geopolitical Forecasting System

## Multi-Agent Strategic Simulation Using:
- Historical Geopolitical Events
- Real Financial Market Data
- Markov Chains
- Monte Carlo Simulation
- Probabilistic Game Theory

INSTALL REQUIRED PACKAGES
"""

# ============================================================
# INSTALL REQUIRED PACKAGES
# ============================================================

!pip install yfinance --quiet

"""IMPORT LIBRARIES"""

# ============================================================
# IMPORT LIBRARIES
# ============================================================

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""Define market tickers"""

# ============================================================
# MARKET TICKERS
# ============================================================

tickers = {

    "Brent_Oil": "BZ=F",
    "SP500": "^GSPC",
    "NIFTY50": "^NSEI",
    "Gold": "GC=F",
    "VIX": "^VIX"
}

"""Download historical market data (1980–Present)"""

# ============================================================
# DOWNLOAD HISTORICAL MARKET DATA
# ============================================================

market_data = {}

for name, ticker in tickers.items():

    data = yf.download(
        ticker,
        start="1980-01-01",
        end="2025-01-01"
    )

    market_data[name] = data

    print(f"{name} downloaded successfully")

"""CHECK SAMPLE DATA"""

# ============================================================
# CHECK SAMPLE DATA
# ============================================================

market_data["Brent_Oil"].head()

"""Create geopolitical events dataset"""

# ============================================================
# USA–IRAN–INDIA GEOPOLITICAL EVENTS
# ============================================================

events = [

    {
        "date": "1979-11-04",
        "usa_action": "Economic Sanctions",
        "iran_action": "Hostage Crisis",
        "india_response": "Neutral Diplomacy",
        "severity": 9,
        "category": "Diplomatic Crisis"
    },

    {
        "date": "1980-09-22",
        "usa_action": "Support Allies",
        "iran_action": "War Mobilization",
        "india_response": "Trade Balancing",
        "severity": 10,
        "category": "War"
    },

    {
        "date": "1988-07-03",
        "usa_action": "Military Action",
        "iran_action": "Regional Escalation",
        "india_response": "Strategic Neutrality",
        "severity": 8,
        "category": "Military Incident"
    },

    {
        "date": "2002-08-14",
        "usa_action": "Diplomatic Pressure",
        "iran_action": "Nuclear Expansion",
        "india_response": "Energy Balancing",
        "severity": 8,
        "category": "Nuclear"
    },

    {
        "date": "2015-07-14",
        "usa_action": "Diplomatic Agreement",
        "iran_action": "Nuclear Compliance",
        "india_response": "Energy Cooperation",
        "severity": 4,
        "category": "Diplomatic Agreement"
    },

    {
        "date": "2018-05-08",
        "usa_action": "JCPOA Withdrawal",
        "iran_action": "Nuclear Expansion",
        "india_response": "Oil Diversification",
        "severity": 8,
        "category": "Sanctions"
    },

    {
        "date": "2020-01-03",
        "usa_action": "Soleimani Strike",
        "iran_action": "Missile Retaliation",
        "india_response": "Strategic Neutrality",
        "severity": 10,
        "category": "Military Strike"
    },

    {
        "date": "2024-04-13",
        "usa_action": "Regional Support",
        "iran_action": "Drone and Missile Attack",
        "india_response": "Energy Security Measures",
        "severity": 9,
        "category": "Direct Conflict"
    }
]

"""Convert to DataFrame"""

# ============================================================
# EVENTS DATAFRAME
# ============================================================

events_df = pd.DataFrame(events)

events_df["date"] = pd.to_datetime(events_df["date"])

events_df

"""Calculate market returns"""

# ============================================================
# CALCULATE DAILY RETURNS
# ============================================================

returns_data = {}

for name, data in market_data.items():

    df = data.copy()

    df["Returns"] = df["Close"].pct_change()

    returns_data[name] = df

"""EVENT IMPACT ANALYSIS FUNCTION"""

# ============================================================
# EVENT IMPACT ANALYSIS FUNCTION
# ============================================================

def analyze_event_impact(
    event_date,
    market_df,
    window_before=10,
    window_after=10
):

    event_date = pd.to_datetime(event_date)

    data = market_df.copy()

    data = data.reset_index()

    event_index = data[data["Date"] >= event_date].index[0]

    start_index = max(0, event_index - window_before)
    end_index = min(len(data) - 1, event_index + window_after)

    window_data = data.iloc[start_index:end_index + 1].copy()

    return window_data

"""Test on oil prices"""

# ============================================================
# TEST EVENT IMPACT
# ============================================================

soleimani_oil = analyze_event_impact(
    "2020-01-03",
    market_data["Brent_Oil"]
)

soleimani_oil.head()

"""Visualize oil reaction"""

# ============================================================
# VISUALIZE OIL REACTION
# ============================================================

plt.figure(figsize=(12,6))

plt.plot(
    soleimani_oil["Date"],
    soleimani_oil["Close"],
    linewidth=2
)

plt.axvline(
    pd.to_datetime("2020-01-03"),
    color="red",
    linestyle="--",
    label="Event Date"
)

plt.title("Brent Oil Reaction to Soleimani Strike")
plt.xlabel("Date")
plt.ylabel("Oil Price")
plt.legend()
plt.grid(True)

plt.show()

"""MULTI-MARKET EVENT ANALYSIS"""

# ============================================================
# MULTI-MARKET EVENT ANALYSIS
# ============================================================

def compare_markets_for_event(
    event_date,
    market_data,
    markets,
    title
):

    plt.figure(figsize=(14,7))

    for market in markets:

        data = analyze_event_impact(
            event_date,
            market_data[market]
        )

        normalized = (
            data["Close"] / data["Close"].iloc[0]
        ) * 100

        plt.plot(
            data["Date"],
            normalized,
            label=market
        )

    plt.axvline(
        pd.to_datetime(event_date),
        color="red",
        linestyle="--",
        label="Event"
    )

    plt.title(title)
    plt.xlabel("Date")
    plt.ylabel("Normalized Index")
    plt.legend()
    plt.grid(True)

    plt.show()

"""Compare all markets"""

# ============================================================
# COMPARE MARKET REACTIONS
# ============================================================

compare_markets_for_event(

    event_date="2020-01-03",

    market_data=market_data,

    markets=[
        "Brent_Oil",
        "SP500",
        "NIFTY50",
        "Gold",
        "VIX"
    ],

    title="Market Reactions to Soleimani Assassination"
)

"""GEOPOLITICAL STATES"""

# ============================================================
# GEOPOLITICAL STATES
# ============================================================

state_mapping = {

    0: "Stable",
    1: "Moderate Tension",
    2: "High Tension",
    3: "Crisis"
}

"""Convert severity into states"""

# ============================================================
# CONVERT SEVERITY TO STATES
# ============================================================

def severity_to_state(severity):

    if severity <= 3:
        return 0

    elif severity <= 6:
        return 1

    elif severity <= 8:
        return 2

    else:
        return 3

"""Apply state classification"""

# ============================================================
# APPLY STATES TO EVENTS
# ============================================================

events_df["state"] = events_df["severity"].apply(
    severity_to_state
)

events_df["state_name"] = events_df["state"].map(
    state_mapping
)

events_df

"""BUILD STATE TRANSITIONS"""

# ============================================================
# BUILD STATE TRANSITIONS
# ============================================================

transitions = []

states = events_df["state"].tolist()

for i in range(len(states) - 1):

    current_state = states[i]
    next_state = states[i + 1]

    transitions.append(
        (current_state, next_state)
    )

transitions

"""TRANSITION MATRIX"""

# ============================================================
# TRANSITION MATRIX
# ============================================================

transition_matrix = np.zeros((4,4))

for current_state, next_state in transitions:

    transition_matrix[current_state][next_state] += 1

for i in range(len(transition_matrix)):

    row_sum = transition_matrix[i].sum()

    if row_sum > 0:
        transition_matrix[i] = (
            transition_matrix[i] / row_sum
        )

transition_matrix

"""Visualize transition matrix"""

# ============================================================
# VISUALIZE TRANSITION MATRIX
# ============================================================

plt.figure(figsize=(8,6))

plt.imshow(
    transition_matrix,
    cmap="Reds"
)

plt.colorbar()

plt.xticks(
    range(4),
    [state_mapping[i] for i in range(4)]
)

plt.yticks(
    range(4),
    [state_mapping[i] for i in range(4)]
)

plt.xlabel("Next State")
plt.ylabel("Current State")

plt.title("Geopolitical State Transition Matrix")

plt.show()

""" STRATEGIC ACTION SPACES"""

# ============================================================
# STRATEGIC ACTION SPACES
# ============================================================

usa_actions = [
    "Diplomatic Negotiation",
    "Economic Sanctions",
    "Military Pressure",
    "Naval Deployment",
    "Cyber Operations"
]

iran_actions = [
    "Diplomatic Response",
    "Proxy Escalation",
    "Missile Demonstration",
    "Oil Route Threat",
    "Nuclear Expansion"
]

india_actions = [
    "Neutral Diplomacy",
    "Oil Diversification",
    "Strategic Mediation",
    "Trade Balancing",
    "Energy Security Measures"
]

"""Define state-based action probabilities"""

# ============================================================
# STATE-BASED STRATEGIC PROBABILITIES
# ============================================================

state_action_probabilities = {

    0: {  # Stable

        "USA": {
            "Diplomatic Negotiation": 0.50,
            "Economic Sanctions": 0.20,
            "Military Pressure": 0.05,
            "Naval Deployment": 0.10,
            "Cyber Operations": 0.15
        },

        "Iran": {
            "Diplomatic Response": 0.55,
            "Proxy Escalation": 0.10,
            "Missile Demonstration": 0.05,
            "Oil Route Threat": 0.05,
            "Nuclear Expansion": 0.25
        },

        "India": {
            "Neutral Diplomacy": 0.40,
            "Oil Diversification": 0.20,
            "Strategic Mediation": 0.25,
            "Trade Balancing": 0.10,
            "Energy Security Measures": 0.05
        }
    },

    1: {  # Moderate Tension

        "USA": {
            "Diplomatic Negotiation": 0.25,
            "Economic Sanctions": 0.35,
            "Military Pressure": 0.15,
            "Naval Deployment": 0.15,
            "Cyber Operations": 0.10
        },

        "Iran": {
            "Diplomatic Response": 0.20,
            "Proxy Escalation": 0.30,
            "Missile Demonstration": 0.15,
            "Oil Route Threat": 0.10,
            "Nuclear Expansion": 0.25
        },

        "India": {
            "Neutral Diplomacy": 0.35,
            "Oil Diversification": 0.25,
            "Strategic Mediation": 0.20,
            "Trade Balancing": 0.10,
            "Energy Security Measures": 0.10
        }
    },

    2: {  # High Tension

        "USA": {
            "Diplomatic Negotiation": 0.10,
            "Economic Sanctions": 0.35,
            "Military Pressure": 0.25,
            "Naval Deployment": 0.20,
            "Cyber Operations": 0.10
        },

        "Iran": {
            "Diplomatic Response": 0.10,
            "Proxy Escalation": 0.35,
            "Missile Demonstration": 0.25,
            "Oil Route Threat": 0.15,
            "Nuclear Expansion": 0.15
        },

        "India": {
            "Neutral Diplomacy": 0.30,
            "Oil Diversification": 0.30,
            "Strategic Mediation": 0.15,
            "Trade Balancing": 0.10,
            "Energy Security Measures": 0.15
        }
    },

    3: {  # Crisis

        "USA": {
            "Diplomatic Negotiation": 0.05,
            "Economic Sanctions": 0.20,
            "Military Pressure": 0.35,
            "Naval Deployment": 0.25,
            "Cyber Operations": 0.15
        },

        "Iran": {
            "Diplomatic Response": 0.05,
            "Proxy Escalation": 0.35,
            "Missile Demonstration": 0.30,
            "Oil Route Threat": 0.20,
            "Nuclear Expansion": 0.10
        },

        "India": {
            "Neutral Diplomacy": 0.20,
            "Oil Diversification": 0.35,
            "Strategic Mediation": 0.10,
            "Trade Balancing": 0.10,
            "Energy Security Measures": 0.25
        }
    }
}

"""ACTION PREDICTION FUNCTION"""

# ============================================================
# ACTION PREDICTION FUNCTION
# ============================================================

def predict_actions(current_state):

    predictions = {}

    for country in ["USA", "Iran", "India"]:

        actions = list(
            state_action_probabilities[current_state][country].keys()
        )

        probabilities = list(
            state_action_probabilities[current_state][country].values()
        )

        chosen_action = np.random.choice(
            actions,
            p=probabilities
        )

        predictions[country] = chosen_action

    return predictions

"""Test action prediction"""

# ============================================================
# TEST ACTION PREDICTION
# ============================================================

current_state = 3

predictions = predict_actions(current_state)

print("Current State:", state_mapping[current_state])

print("\nPredicted Strategic Actions:\n")

for country, action in predictions.items():

    print(country, "→", action)

"""NEXT STATE PREDICTION"""

# ============================================================
# NEXT STATE PREDICTION
# ============================================================

def predict_next_state(current_state):

    probabilities = transition_matrix[current_state]

    next_state = np.random.choice(
        [0,1,2,3],
        p=probabilities
    )

    return next_state

"""MARKET IMPACT ASSUMPTIONS"""

# ============================================================
# MARKET IMPACT ASSUMPTIONS
# ============================================================

market_impacts = {

    0: {  # Stable
        "oil": 0.2,
        "sp500": 0.5,
        "nifty": 0.5,
        "gold": -0.2,
        "vix": -0.3
    },

    1: {  # Moderate Tension
        "oil": 1.0,
        "sp500": -0.5,
        "nifty": -0.8,
        "gold": 0.7,
        "vix": 1.0
    },

    2: {  # High Tension
        "oil": 3.0,
        "sp500": -2.0,
        "nifty": -2.5,
        "gold": 2.0,
        "vix": 4.0
    },

    3: {  # Crisis
        "oil": 6.0,
        "sp500": -5.0,
        "nifty": -6.0,
        "gold": 4.0,
        "vix": 8.0
    }
}

"""FUTURE SCENARIO SIMULATION ENGINE"""

# ============================================================
# FUTURE SCENARIO SIMULATION ENGINE
# ============================================================

def simulate_future(
    start_state,
    steps=20
):

    simulation_results = []

    current_state = start_state

    for step in range(steps):

        predicted_actions = predict_actions(current_state)

        impacts = market_impacts[current_state]

        simulation_results.append({

            "step": step,

            "state": state_mapping[current_state],

            "USA_action": predicted_actions["USA"],

            "Iran_action": predicted_actions["Iran"],

            "India_action": predicted_actions["India"],

            "Oil_Impact_%": impacts["oil"],

            "SP500_Impact_%": impacts["sp500"],

            "NIFTY50_Impact_%": impacts["nifty"],

            "Gold_Impact_%": impacts["gold"],

            "VIX_Impact_%": impacts["vix"]
        })

        current_state = predict_next_state(current_state)

    return pd.DataFrame(simulation_results)

"""RUN FUTURE SIMULATION"""

# ============================================================
# RUN FUTURE SIMULATION
# ============================================================

future_simulation = simulate_future(
    start_state=2,
    steps=20
)

future_simulation

"""VISUALIZE STATE EVOLUTION"""

# ============================================================
# VISUALIZE STATE EVOLUTION
# ============================================================

state_numbers = []

for state_name in future_simulation["state"]:

    for number, name in state_mapping.items():

        if name == state_name:
            state_numbers.append(number)

plt.figure(figsize=(14,6))

plt.plot(
    future_simulation["step"],
    state_numbers,
    marker="o"
)

plt.yticks(
    [0,1,2,3],
    ["Stable", "Moderate", "High", "Crisis"]
)

plt.xlabel("Simulation Step")
plt.ylabel("Geopolitical State")

plt.title("Simulated Geopolitical Evolution")

plt.grid(True)

plt.show()

"""MONTE CARLO SIMULATION ENGINE"""

# ============================================================
# MONTE CARLO SIMULATION ENGINE
# ============================================================

def monte_carlo_simulation(
    start_state,
    simulations=500,
    steps=20
):

    all_simulations = []

    for sim in range(simulations):

        result = simulate_future(
            start_state=start_state,
            steps=steps
        )

        result["simulation_id"] = sim

        all_simulations.append(result)

    combined_results = pd.concat(
        all_simulations,
        ignore_index=True
    )

    return combined_results

"""Run Monte Carlo simulation"""

# ============================================================
# RUN MONTE CARLO
# ============================================================

mc_results = monte_carlo_simulation(
    start_state=2,
    simulations=500,
    steps=20
)

mc_results.head()

"""CRISIS PROBABILITY"""

# ============================================================
# CRISIS PROBABILITY
# ============================================================

crisis_count = (
    mc_results["state"] == "Crisis"
).sum()

total_states = len(mc_results)

crisis_probability = (
    crisis_count / total_states
) * 100

print(
    f"Crisis Probability: {crisis_probability:.2f}%"
)

"""MOST COMMON STRATEGIC ACTIONS"""

# ============================================================
# MOST COMMON STRATEGIC ACTIONS
# ============================================================

print("Most Common USA Actions:\n")
print(
    mc_results["USA_action"].value_counts()
)

print("\nMost Common Iran Actions:\n")
print(
    mc_results["Iran_action"].value_counts()
)

print("\nMost Common India Actions:\n")
print(
    mc_results["India_action"].value_counts()
)

"""Market impact distributions"""

# ============================================================
# MARKET IMPACT DISTRIBUTIONS
# ============================================================

plt.figure(figsize=(12,6))

plt.hist(
    mc_results["Oil_Impact_%"],
    bins=20,
    alpha=0.7
)

plt.title("Distribution of Oil Market Impacts")

plt.xlabel("Oil Impact (%)")
plt.ylabel("Frequency")

plt.grid(True)

plt.show()

"""State distribution analysis"""

# ============================================================
# GEOPOLITICAL STATE DISTRIBUTION
# ============================================================

state_distribution = (
    mc_results["state"]
    .value_counts(normalize=True)
    * 100
)

print(state_distribution)

"""Visualize state probabilities"""

# ============================================================
# VISUALIZE STATE PROBABILITIES
# ============================================================

state_distribution.plot(
    kind="bar",
    figsize=(10,6)
)

plt.title("Geopolitical State Probability Distribution")

plt.ylabel("Probability (%)")

plt.grid(True)

plt.show()

"""ADAPTIVE TENSION MEMORY"""

# ============================================================
# ADAPTIVE TENSION MEMORY
# ============================================================

tension_memory = {

    "recent_crises": 0,
    "recent_high_tension": 0,
    "recent_stable_periods": 0
}

"""UPDATE TENSION MEMORY"""

# ============================================================
# UPDATE TENSION MEMORY
# ============================================================

def update_tension_memory(current_state):

    global tension_memory

    if current_state == 3:
        tension_memory["recent_crises"] += 1

    elif current_state == 2:
        tension_memory["recent_high_tension"] += 1

    elif current_state == 0:
        tension_memory["recent_stable_periods"] += 1

"""ADAPTIVE TRANSITION MODEL"""

# ============================================================
# ADAPTIVE TRANSITION MODEL
# ============================================================

def adaptive_next_state(current_state):

    probabilities = transition_matrix[current_state].copy()

    crisis_pressure = (
        tension_memory["recent_crises"] * 0.03
    )

    high_tension_pressure = (
        tension_memory["recent_high_tension"] * 0.02
    )

    stability_pressure = (
        tension_memory["recent_stable_periods"] * 0.02
    )

    # Increase crisis probability
    probabilities[3] += crisis_pressure

    # Increase high tension probability
    probabilities[2] += high_tension_pressure

    # Increase stability probability
    probabilities[0] += stability_pressure

    # Normalize probabilities
    probabilities = probabilities / probabilities.sum()

    next_state = np.random.choice(
        [0,1,2,3],
        p=probabilities
    )

    return next_state

"""ADAPTIVE FUTURE SIMULATION"""

# ============================================================
# ADAPTIVE FUTURE SIMULATION
# ============================================================

def adaptive_simulation(
    start_state,
    steps=20
):

    global tension_memory

    tension_memory = {

        "recent_crises": 0,
        "recent_high_tension": 0,
        "recent_stable_periods": 0
    }

    results = []

    current_state = start_state

    for step in range(steps):

        update_tension_memory(current_state)

        predicted_actions = predict_actions(current_state)

        impacts = market_impacts[current_state]

        results.append({

            "step": step,

            "state": state_mapping[current_state],

            "USA_action": predicted_actions["USA"],

            "Iran_action": predicted_actions["Iran"],

            "India_action": predicted_actions["India"],

            "Oil_Impact_%": impacts["oil"],

            "SP500_Impact_%": impacts["sp500"],

            "NIFTY50_Impact_%": impacts["nifty"],

            "Gold_Impact_%": impacts["gold"],

            "VIX_Impact_%": impacts["vix"]
        })

        current_state = adaptive_next_state(
            current_state
        )

    return pd.DataFrame(results)

"""RUN ADAPTIVE SIMULATION"""

# ============================================================
# RUN ADAPTIVE SIMULATION
# ============================================================

adaptive_results = adaptive_simulation(
    start_state=2,
    steps=30
)

adaptive_results

"""VISUALIZE ADAPTIVE EVOLUTION"""

# ============================================================
# VISUALIZE ADAPTIVE EVOLUTION
# ============================================================

adaptive_state_numbers = []

for state_name in adaptive_results["state"]:

    for number, name in state_mapping.items():

        if name == state_name:
            adaptive_state_numbers.append(number)

plt.figure(figsize=(14,6))

plt.plot(
    adaptive_results["step"],
    adaptive_state_numbers,
    marker="o"
)

plt.yticks(
    [0,1,2,3],
    ["Stable", "Moderate", "High", "Crisis"]
)

plt.xlabel("Simulation Step")
plt.ylabel("Geopolitical State")

plt.title("Adaptive Geopolitical Evolution")

plt.grid(True)

plt.show()

"""BAYESIAN PRIOR PROBABILITIES"""

# ============================================================
# BAYESIAN PRIOR PROBABILITIES
# ============================================================

bayesian_state_probabilities = {

    0: 0.20,  # Stable
    1: 0.35,  # Moderate
    2: 0.30,  # High Tension
    3: 0.15   # Crisis
}

"""EVIDENCE LIKELIHOODS"""

# ============================================================
# EVIDENCE LIKELIHOODS
# ============================================================

evidence_likelihoods = {

    "Missile Strike": {
        0: 0.01,
        1: 0.10,
        2: 0.40,
        3: 0.80
    },

    "Diplomatic Agreement": {
        0: 0.70,
        1: 0.50,
        2: 0.20,
        3: 0.05
    },

    "Oil Route Threat": {
        0: 0.02,
        1: 0.20,
        2: 0.60,
        3: 0.75
    },

    "Economic Sanctions": {
        0: 0.10,
        1: 0.45,
        2: 0.55,
        3: 0.30
    },

    "Naval Deployment": {
        0: 0.05,
        1: 0.30,
        2: 0.55,
        3: 0.60
    }
}

"""BAYESIAN UPDATE FUNCTION"""

# ============================================================
# BAYESIAN UPDATE FUNCTION
# ============================================================

def bayesian_update(priors, evidence):

    likelihoods = evidence_likelihoods[evidence]

    posterior = {}

    total_probability = 0

    for state in priors:

        posterior[state] = (
            priors[state]
            * likelihoods[state]
        )

        total_probability += posterior[state]

    # Normalize probabilities
    for state in posterior:

        posterior[state] /= total_probability

    return posterior

# ============================================================
# TEST BAYESIAN UPDATE
# ============================================================

updated_probabilities = bayesian_update(
    bayesian_state_probabilities,
    "Missile Strike"
)

updated_probabilities

# ============================================================
# VISUALIZE BAYESIAN UPDATE
# ============================================================

states = [
    state_mapping[i]
    for i in updated_probabilities.keys()
]

values = list(
    updated_probabilities.values()
)

plt.figure(figsize=(10,6))

plt.bar(states, values)

plt.title("Updated Geopolitical Probabilities")

plt.ylabel("Probability")

plt.grid(True)

plt.show()

# ============================================================
# REWARD SYSTEM
# ============================================================

reward_system = {

    "USA": {

        "Stable": 5,
        "Moderate Tension": 2,
        "High Tension": -2,
        "Crisis": -5
    },

    "Iran": {

        "Stable": 3,
        "Moderate Tension": 2,
        "High Tension": -1,
        "Crisis": -4
    },

    "India": {

        "Stable": 6,
        "Moderate Tension": 1,
        "High Tension": -3,
        "Crisis": -6
    }
}

# ============================================================
# INITIALIZE Q-VALUES
# ============================================================

q_values = {

    "USA": {},
    "Iran": {},
    "India": {}
}

# ============================================================
# INITIALIZE ACTION VALUES
# ============================================================

for state in [0,1,2,3]:

    state_name = state_mapping[state]

    q_values["USA"][state_name] = {
        action: 0
        for action in usa_actions
    }

    q_values["Iran"][state_name] = {
        action: 0
        for action in iran_actions
    }

    q_values["India"][state_name] = {
        action: 0
        for action in india_actions
    }

# ============================================================
# Q-LEARNING UPDATE
# ============================================================

def update_q_value(
    country,
    state_name,
    action,
    reward,
    learning_rate=0.1
):

    current_q = q_values[country][state_name][action]

    new_q = current_q + (
        learning_rate
        * (reward - current_q)
    )

    q_values[country][state_name][action] = new_q

# ============================================================
# STRATEGIC LEARNING SIMULATION
# ============================================================

def reinforcement_learning_simulation(
    episodes=500
):

    for episode in range(episodes):

        current_state = np.random.choice([0,1,2,3])

        state_name = state_mapping[current_state]

        predictions = predict_actions(current_state)

        usa_action = predictions["USA"]
        iran_action = predictions["Iran"]
        india_action = predictions["India"]

        usa_reward = reward_system["USA"][state_name]
        iran_reward = reward_system["Iran"][state_name]
        india_reward = reward_system["India"][state_name]

        update_q_value(
            "USA",
            state_name,
            usa_action,
            usa_reward
        )

        update_q_value(
            "Iran",
            state_name,
            iran_action,
            iran_reward
        )

        update_q_value(
            "India",
            state_name,
            india_action,
            india_reward
        )

# ============================================================
# TRAIN RL AGENTS
# ============================================================

reinforcement_learning_simulation(
    episodes=1000
)

# ============================================================
# VIEW LEARNED STRATEGIES
# ============================================================

q_values

# ============================================================
# INSTALL NLP PACKAGE
# ============================================================

!pip install vaderSentiment --quiet

# ============================================================
# IMPORT SENTIMENT ANALYZER
# ============================================================

from vaderSentiment.vaderSentiment import (
    SentimentIntensityAnalyzer
)

analyzer = SentimentIntensityAnalyzer()

# ============================================================
# SAMPLE GEOPOLITICAL HEADLINES
# ============================================================

headlines = [

    "Iran threatens disruption of key oil shipping routes",

    "USA announces additional sanctions on Iran",

    "India urges diplomatic de-escalation in Middle East",

    "Missile strikes increase tensions in the Gulf region",

    "Diplomatic talks resume between Iran and Western powers"
]

# ============================================================
# HEADLINE SENTIMENT ANALYSIS
# ============================================================

headline_sentiments = []

for headline in headlines:

    sentiment = analyzer.polarity_scores(
        headline
    )

    headline_sentiments.append({

        "headline": headline,

        "compound_score": sentiment["compound"]
    })

sentiment_df = pd.DataFrame(
    headline_sentiments
)

sentiment_df

# ============================================================
# SENTIMENT-BASED TENSION SIGNAL
# ============================================================

def sentiment_to_tension(score):

    if score >= 0.4:
        return "Stable"

    elif score >= 0:
        return "Moderate Tension"

    elif score >= -0.4:
        return "High Tension"

    else:
        return "Crisis"

# ============================================================
# APPLY TENSION CLASSIFICATION
# ============================================================

sentiment_df["predicted_state"] = sentiment_df[
    "compound_score"
].apply(sentiment_to_tension)

sentiment_df

# ============================================================
# NEWS-DRIVEN STATE UPDATE
# ============================================================

def update_probabilities_from_news(
    state_probabilities,
    predicted_state
):

    updated = state_probabilities.copy()

    if predicted_state == "Crisis":
        updated[3] += 0.15

    elif predicted_state == "High Tension":
        updated[2] += 0.10

    elif predicted_state == "Stable":
        updated[0] += 0.10

    total = sum(updated.values())

    for state in updated:
        updated[state] /= total

    return updated

# ============================================================
# TEST NEWS-DRIVEN UPDATE
# ============================================================

current_probs = bayesian_state_probabilities.copy()

headline_state = "Crisis"

updated_probs = update_probabilities_from_news(
    current_probs,
    headline_state
)

updated_probs

# ============================================================
# SAMPLE STATE FROM PROBABILITIES
# ============================================================

def sample_state(probabilities):

    states = list(probabilities.keys())

    probs = list(probabilities.values())

    return np.random.choice(
        states,
        p=probs
    )

# ============================================================
# UNIFIED FORECASTING ENGINE
# ============================================================

def unified_forecast_engine(

    current_state,
    headline,
    simulation_steps=15

):

    sentiment = analyzer.polarity_scores(
        headline
    )["compound"]

    predicted_state_name = sentiment_to_tension(
        sentiment
    )

    updated_probabilities = (
        update_probabilities_from_news(
            bayesian_state_probabilities.copy(),
            predicted_state_name
        )
    )

    simulation_results = []

    state = sample_state(
        updated_probabilities
    )

    for step in range(simulation_steps):

        actions = predict_actions(state)

        impacts = market_impacts[state]

        simulation_results.append({

            "step": step,

            "state": state_mapping[state],

            "USA_action": actions["USA"],

            "Iran_action": actions["Iran"],

            "India_action": actions["India"],

            "Oil_Impact_%": impacts["oil"],

            "SP500_Impact_%": impacts["sp500"],

            "NIFTY50_Impact_%": impacts["nifty"],

            "Gold_Impact_%": impacts["gold"],

            "VIX_Impact_%": impacts["vix"]
        })

        state = adaptive_next_state(state)

    return pd.DataFrame(simulation_results)

# ============================================================
# TEST UNIFIED ENGINE
# ============================================================

headline = (
    "Iran threatens major retaliation "
    "after new sanctions by the USA"
)

forecast = unified_forecast_engine(

    current_state=2,
    headline=headline,
    simulation_steps=20
)

forecast

# ============================================================
# VISUALIZE FUTURE OIL IMPACTS
# ============================================================

plt.figure(figsize=(12,6))

plt.plot(
    forecast["step"],
    forecast["Oil_Impact_%"],
    marker="o"
)

plt.title("Forecasted Oil Market Impacts")

plt.xlabel("Simulation Step")

plt.ylabel("Oil Impact (%)")

plt.grid(True)

plt.show()

# ============================================================
# VISUALIZE FUTURE STATES
# ============================================================

forecast_states = []

for state_name in forecast["state"]:

    for num, name in state_mapping.items():

        if name == state_name:

            forecast_states.append(num)

plt.figure(figsize=(12,6))

plt.plot(
    forecast["step"],
    forecast_states,
    marker="o"
)

plt.yticks(
    [0,1,2,3],
    ["Stable", "Moderate", "High", "Crisis"]
)

plt.title("Forecasted Geopolitical Evolution")

plt.xlabel("Simulation Step")

plt.ylabel("State")

plt.grid(True)

plt.show()

